import RPi.GPIO as GPIO
import time


GPIO.setmode(GPIO.BOARD)
GPIO.setup(3,GPIO.OUT)
GPIO.setup(5,GPIO.OUT)
GPIO.setup(7,GPIO.OUT)
GPIO.setup(11,GPIO.OUT)
GPIO.setup(13,GPIO.OUT)
GPIO.setup(15,GPIO.OUT)
GPIO.setup(19,GPIO.OUT)
GPIO.setup(21,GPIO.OUT)
GPIO.setup(23,GPIO.OUT)


lucesGPIOs={'A':3, 'B': 5,'C':7,'D':11,'E':13,'F':15,'G':21,'H':19,'I':23}

while True:
	GPIO.output(lucesGPIOs['A'],1)
	time.sleep(1)
	GPIO.output(lucesGPIOs['A'],0)
	time.sleep(1)
	GPIO.output(lucesGPIOs['B'],1)
	time.sleep(1)
	GPIO.output(lucesGPIOs['B'],0)
	time.sleep(1)
	GPIO.output(lucesGPIOs['C'],1)
	time.sleep(1)
	GPIO.output(lucesGPIOs['C'],0)
	time.sleep(1)
	GPIO.output(lucesGPIOs['D'],1)
	time.sleep(1)
	GPIO.output(lucesGPIOs['D'],0)
	time.sleep(1)
	GPIO.output(lucesGPIOs['E'],1)
	time.sleep(1)
	GPIO.output(lucesGPIOs['E'],0)
	time.sleep(1)
	GPIO.output(lucesGPIOs['F'],1)
	time.sleep(1)
	GPIO.output(lucesGPIOs['F'],0)
	time.sleep(1)
	GPIO.output(lucesGPIOs['G'],1)
	time.sleep(1)
	GPIO.output(lucesGPIOs['G'],0)
	time.sleep(1)
	GPIO.output(lucesGPIOs['H'],1)
	time.sleep(1)
	GPIO.output(lucesGPIOs['H'],0)
	time.sleep(1)
	GPIO.output(lucesGPIOs['I'],1)
	time.sleep(1)
	GPIO.output(lucesGPIOs['I'],0)
	time.sleep(1)
